### ISSUE TITLE
Limits

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/pool-evm-single-l1#12]
The main goal is to create an additional barrier for illicit activities and at the same time not to impair ability for regular users. Since the main feature to distinguish illicit transaction right now is the amount, it's seems reasonable to set following restictions:

1. A single operation ( deposit or withdrawal ) cannot exceed X1
2. A single address can't deposit more than X2 during a single period of 24 hours
3. A single address can't withdraw more than X2 during a single period of 24 hours

## Implementation

1. Add a mutable daily quota value to the Pool state and constructor
2. Add a map of all the addresses that have transacted that day
3. When a user performs a transaction check that map entry doesn't exist or contains enough quota
4. Process transaction
5. Reduce the quota

**Comment by ulyanas** [comment]
Suggestion: 

1. A single deposit cannot exceed X1
2. A single address can't deposit more than X2 during a single period of 24 hours 
3. All deposits from all addresses  cannot exceed X3 during a period of 24 hours

**Comment by ulyanas** [comment]
Upd. on the limits
• Single-transaction  deposit cap - 10,000 BOB
• Single-address daily asset deposit cap - 10,000 BOB
• System-wide daily asset deposit cap - 100,000 BOB
• Pool size - 1,000,000 BOB
